version: '3.8'
services:
    ip_admins_interface:
        container_name: ip_admins_interface
        build: ./admins_interface
        ports:
            - "5101:80"

    ip_clients:
        container_name: ip_clients
        build: ./clients
    
    ip_couriers:
        container_name: ip_couriers
        build: ./couriers
    
    ip_orders:
        container_name: ip_orders
        build: ./orders
    
    ip_couriers_interface:
        container_name: ip_couriers_interface
        build: ./couriers_interface
        ports:
            - "5102:80"
    
    rabbit_mq:
        image: "rabbitmq"
        container_name: rabbit_mq
    
    ip_signs:
        container_name: ip_signs
        build: ./signs
        depends_on: 
           - rabbit_mq
    
    ip_admins_db:
        container_name: ip_admins_db
        build: ./ip_admins_db
        ports:
            - "3308:3306"
    
    ip_clients_db:
        container_name: ip_clients_db
        build: ./ip_clients_db
        ports:
            - "3309:3306"

    ip_couriers_db:
        container_name: ip_couriers_db
        build: ./ip_couriers_db
        ports:
            - "3310:3306"

    ip_orders_db:
        container_name: ip_orders_db
        build: ./ip_orders_db
        ports:
            - "3307:3306"